// src/app/niqqud-keyboard/niqqud-keyboard.component.ts
import {Component, Input, OnChanges, SimpleChanges} from '@angular/core';
import {LetterInstance, Niqqud, NIQQUD_BY_GROUPS} from '../hebrew-letter';

@Component({
    selector: 'niqqud-keyboard',
    templateUrl: './niqqud-keyboard.component.html'
})
export class NiqqudKeyboardComponent implements OnChanges {
    @Input()
    selectedLetter: LetterInstance;

    allNiqqudByGroups: Niqqud[][];

    letterWithNiqqud(niqqud: Niqqud): LetterInstance {
        return new LetterInstance(this.selectedLetter.consonant, [niqqud]);
    }

    ngOnChanges(changes: SimpleChanges): void {
        if (changes['selectedLetter']) {
            this.regenerateAvailableNiqqud();
        }
    }

    private regenerateAvailableNiqqud() {
        const filter = (v) => v.isApplicableToLetter(this.selectedLetter.consonant);

        this.allNiqqudByGroups = NIQQUD_BY_GROUPS.map((x) => x.filter(filter)).filter((g) => g.length);
    }
}

<ul class="hebrew-text" *ngFor="let group of allNiqqudByGroups; let f = first" [class.has-flourish-above]="f">
    <li class="hebrew-text-letterblock" *ngFor="let niqqud of group"
         [class.is-selected]="selectedLetter.hasNiqqud(niqqud)"
         (click)="selectedLetter.toggleNiqqud(niqqud)"
         unselectable="on">
        {{letterWithNiqqud(niqqud).representation}}
    </li>
</ul>

// src/niqqud-keyboard.tsx
import { Component } from "preact";
import { LetterInstance, Niqqud } from "./hebrew-letter";

export interface NiqqudKeyboardProps {
    letter: LetterInstance;
    onToggle: (niqqud: Niqqud) => void;
}

export class NiqqudKeyboard extends Component<NiqqudKeyboardProps> {
    render() {
        return <div class="niqqud-keyboard">
            {this.props.letter.applicableNiqqudByGroups.map((group, group_idx) => 
                <ul class={'hebrew-text' + (group_idx===0 ? ' has-flourish-above' : '')}>{
                    group.map((niqqud, niqqud_idx) => 
                        <li
                            class={
                                'hebrew-text-letterblock'
                                + (this.props.letter.hasNiqqud(niqqud) ? ' is-selected' : '')
                            }
                            onClick={this.props.onToggle.bind(null, niqqud)}
                        >
                            {this.props.letter.consonant + niqqud.representation}
                        </li>
                    )
                }</ul>
            )}
        </div>;
    }
}
